// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43q-7E-INzCXtTBQpbKArb1199yZsfok',
    appId: '1:437536904225:web:2251becd02fc7876a2bf60',
    messagingSenderId: '437536904225',
    projectId: 'prepwise-1af86',
    authDomain: 'prepwise-1af86.firebaseapp.com',
    storageBucket: 'prepwise-1af86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJo_VSfoHcjTdmW0syu59gYbrM70ehcNk',
    appId: '1:437536904225:android:6a32eb3eab785e98a2bf60',
    messagingSenderId: '437536904225',
    projectId: 'prepwise-1af86',
    storageBucket: 'prepwise-1af86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-x7bm9wbGkKaKWtjT2ES8msO3jC-wjk',
    appId: '1:437536904225:ios:625cb6e96a7c2c67a2bf60',
    messagingSenderId: '437536904225',
    projectId: 'prepwise-1af86',
    storageBucket: 'prepwise-1af86.firebasestorage.app',
    iosBundleId: 'com.example.prepwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-x7bm9wbGkKaKWtjT2ES8msO3jC-wjk',
    appId: '1:437536904225:ios:625cb6e96a7c2c67a2bf60',
    messagingSenderId: '437536904225',
    projectId: 'prepwise-1af86',
    storageBucket: 'prepwise-1af86.firebasestorage.app',
    iosBundleId: 'com.example.prepwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD43q-7E-INzCXtTBQpbKArb1199yZsfok',
    appId: '1:437536904225:web:7dfb94969d802e1aa2bf60',
    messagingSenderId: '437536904225',
    projectId: 'prepwise-1af86',
    authDomain: 'prepwise-1af86.firebaseapp.com',
    storageBucket: 'prepwise-1af86.firebasestorage.app',
  );
}
